### ISSUE TITLE
Generic style rule is breaking automatic updating of iframe height

### ISSUE THREAD

**Issue by zinkkrysty** [nprapps/pym.js#168]
If I have this style in head:

```css
iframe { 
  height: 100%; /* or any other value */
}
```

Then the resizing of the iframe does not work, since the rule always overrides the `height` attribute. I suggest this plugin is also/instead updating `iframe.style.height`, which is harder to override accidentally.
